# **Import** Libraries

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
!pip install ydata-profiling -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.8/400.8 kB 26.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.7/296.7 kB 21.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 84.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 682.5/682.5 kB 37.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.4/105.4 kB 8.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.0/72.0 kB 5.3 MB/s eta 0:00:00

In [5]:
from ydata_profiling import ProfileReport
profile = ProfileReport(df_film, title="Pandas Profiling Report")
profile.to_file("your_report.html")

/tmp/ipykernel_671/1955466658.py:1: DeprecationWarning:
    `import ydata_profiling` is deprecated and will not receive more updates.
    Please install fg-data-profiling via `pip install fg-data-profiling` and use `import data_profiling` instead.

  from ydata_profiling import ProfileReport

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]
 50%|█████     | 2/4 [00:00<00:00, 14.87it/s]
100%|██████████| 4/4 [00:09<00:00,  2.42s/it]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

# **Exploring** data

In [12]:
df_film = pd.read_csv("tmdb_5000_credits.csv")
pd.set_option('display.max_colwidth', None)
df_film.head(1)

   movie_id   title  \
0     19995  Avatar

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      cast  \

# Change from json to table

In [15]:
import ast
df_film['cast'] = df_film['cast'].apply(ast.literal_eval)
df_film['crew'] = df_film['crew'].apply(ast.literal_eval)

In [16]:
type(df_film['cast'].iloc[0])

list

# changing **cast** column

In [18]:
df_cast_exploded = df_film.explode('cast')
df_cast_clean = pd.json_normalize(df_cast_exploded['cast'])

df_cast_clean['movie_id'] = df_cast_exploded['movie_id'].values
df_cast_clean['title'] = df_cast_exploded['title'].values
df_cast_clean.head()

,cast_id,character,credit_id,gender,id,name,order,movie_id,title
0,242.0,Jake Sully,5602a8a7c3a3685532001c9a,2.0,65731.0,Sam Worthington,0.0,19995,Avatar
1,3.0,Neytiri,52fe48009251416c750ac9cb,1.0,8691.0,Zoe Saldana,1.0,19995,Avatar
2,25.0,Dr. Grace Augustine,52fe48009251416c750aca39,1.0,10205.0,Sigourney Weaver,2.0,19995,Avatar
3,4.0,Col. Quaritch,52fe48009251416c750ac9cf,2.0,32747.0,Stephen Lang,3.0,19995,Avatar
4,5.0,Trudy Chacon,52fe48009251416c750ac9d3,1.0,17647.0,Michelle Rodriguez,4.0,19995,Avatar

# changing **crew** column

In [20]:
df_crew_exploded = df_film.explode('crew')
df_crew_clean = pd.json_normalize(df_crew_exploded['crew'])
df_crew_clean['movie_id'] = df_crew_exploded['movie_id'].values
df_crew_clean['title'] = df_crew_exploded['title'].values
df_crew_clean.head()

,credit_id,department,gender,id,job,name,movie_id,title
0,52fe48009251416c750aca23,Editing,0.0,1721.0,Editor,Stephen E. Rivkin,19995,Avatar
1,539c47ecc3a36810e3001f87,Art,2.0,496.0,Production Design,Rick Carter,19995,Avatar
2,54491c89c3a3680fb4001cf7,Sound,0.0,900.0,Sound Designer,Christopher Boyes,19995,Avatar
3,54491cb70e0a267480001bd0,Sound,0.0,900.0,Supervising Sound Editor,Christopher Boyes,19995,Avatar
4,539c4a4cc3a36810c9002101,Production,1.0,1262.0,Casting,Mali Finn,19995,Avatar

# 2 sheets cleaned **connected** by id

In [21]:
with pd.ExcelWriter("tmdb_credits_cleaned.xlsx", engine='openpyxl') as writer:
    df_cast_clean.to_excel(writer, sheet_name="Cast_Details", index=False)
    df_crew_clean.to_excel(writer, sheet_name="Crew_Details", index=False)

In [22]:
print("saved successfully tmdb_credits_cleaned.xlsx")

saved successfully tmdb_credits_cleaned.xlsx